In [7]:
import pandas as pd
from math import *

In [37]:
df = pd.read_json('notes.json')

In [38]:
df.head()

   index note  slot_position  sounding_length  frequency
0      1    F          938.0            837.0   87.30706
1      2    G          927.0            826.0   97.99886
2      3    A          916.5            815.5  110.00000
3      4   Bb          902.5            801.5  116.54090
4      5    B          888.5            787.5  123.47080

In [39]:
1/(0.4*df['sounding_length'])*sqrt((3)/(pi*8746))

0     0.000031
1     0.000032
2     0.000032
3     0.000033
4     0.000033
5     0.000034
6     0.000036
7     0.000038
8     0.000039
9     0.000041
10    0.000044
11    0.000046
12    0.000047
13    0.000050
14    0.000053
15    0.000054
16    0.000058
17    0.000061
18    0.000065
19    0.000066
20    0.000070
21    0.000075
22    0.000078
23    0.000082
24    0.000088
25    0.000093
26    0.000097
27    0.000102
28    0.000108
29    0.000115
30    0.000121
31    0.000129
32    0.000137
33    0.000146
34    0.000154
35    0.000162
36    0.000174
37    0.000186
38    0.000199
39    0.000208
40    0.000225
41    0.000239
42    0.000256
43    0.000267
44    0.000285
45    0.000307
46    0.000329
Name: sounding_length, dtype: float64

In [40]:
df[df['sounding_length'] + 101 != df['slot_position']]

    index note  slot_position  sounding_length  frequency
11     12   f#          665.5            565.0   184.9972
15     16   bb          582.0            481.5   233.0819
26     27   a1          371.0            270.5   440.0000
31     32   d2          302.5            202.0   587.3295
33     34   e2          280.0            179.5   659.2551
36     37   g2          251.0            150.5   783.9909